groups:
  - id: 0
    name: Kitchen_waste
    aliases: [potato, daikon, carrot]

  - id: 1
    name: Recyclable_waste
    aliases: [bottle, can]

  - id: 2
    name: Hazardous_waste
    aliases: [battery, drug, inner_packing]

  - id: 3
    name: Other_waste
    aliases: [tile, stone, brick]
