links:
  - train_id: yolo_v12n_e300
    deploy_id: raspi_yolo_v12n

  - train_id: fasterrcnn_mobilenet
    deploy_id: x86_fast_rcnn

  - train_id: yolo_v12s_large
    deploy_id: rk3588_yolo_onnx

  - train_id: fasterrcnn_resnet50
    deploy_id: x86_fast_rcnn
